/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInfoRouteImport } from './routes/_authenticated/info'
import { Route as AuthenticatedLandingEditorRouteImport } from './routes/_authenticated/landing-editor'
import { Route as AuthenticatedNewPasswordRouteImport } from './routes/_authenticated/new-password'
import { Route as AuthenticatedOverlayCreatorRouteImport } from './routes/_authenticated/overlay-creator'
import { Route as AuthenticatedPlansRouteImport } from './routes/_authenticated/plans'
import { Route as AuthenticatedRechargeRouteImport } from './routes/_authenticated/recharge'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated/referrals'
import { Route as AuthenticatedEditorProjectIdRouteImport } from './routes/_authenticated/editor.$projectId'
import { Route as ApiPublicLandingImageSplatRouteImport } from './routes/api/public/landing-image.$'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInfoRoute = AuthenticatedInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLandingEditorRoute =
  AuthenticatedLandingEditorRouteImport.update({
    id: '/landing-editor',
    path: '/landing-editor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNewPasswordRoute =
  AuthenticatedNewPasswordRouteImport.update({
    id: '/new-password',
    path: '/new-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOverlayCreatorRoute =
  AuthenticatedOverlayCreatorRouteImport.update({
    id: '/overlay-creator',
    path: '/overlay-creator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlansRoute = AuthenticatedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRechargeRoute = AuthenticatedRechargeRouteImport.update({
  id: '/recharge',
  path: '/recharge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEditorProjectIdRoute =
  AuthenticatedEditorProjectIdRouteImport.update({
    id: '/editor/$projectId',
    path: '/editor/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicLandingImageSplatRoute =
  ApiPublicLandingImageSplatRouteImport.update({
    id: '/api/public/landing-image/$',
    path: '/api/public/landing-image/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/info': typeof AuthenticatedInfoRoute
  '/landing-editor': typeof AuthenticatedLandingEditorRoute
  '/new-password': typeof AuthenticatedNewPasswordRoute
  '/overlay-creator': typeof AuthenticatedOverlayCreatorRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/recharge': typeof AuthenticatedRechargeRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/editor/$projectId': typeof AuthenticatedEditorProjectIdRoute
  '/api/public/landing-image/$': typeof ApiPublicLandingImageSplatRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/info': typeof AuthenticatedInfoRoute
  '/landing-editor': typeof AuthenticatedLandingEditorRoute
  '/new-password': typeof AuthenticatedNewPasswordRoute
  '/overlay-creator': typeof AuthenticatedOverlayCreatorRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/recharge': typeof AuthenticatedRechargeRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/editor/$projectId': typeof AuthenticatedEditorProjectIdRoute
  '/api/public/landing-image/$': typeof ApiPublicLandingImageSplatRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/info': typeof AuthenticatedInfoRoute
  '/_authenticated/landing-editor': typeof AuthenticatedLandingEditorRoute
  '/_authenticated/new-password': typeof AuthenticatedNewPasswordRoute
  '/_authenticated/overlay-creator': typeof AuthenticatedOverlayCreatorRoute
  '/_authenticated/plans': typeof AuthenticatedPlansRoute
  '/_authenticated/recharge': typeof AuthenticatedRechargeRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/_authenticated/editor/$projectId': typeof AuthenticatedEditorProjectIdRoute
  '/api/public/landing-image/$': typeof ApiPublicLandingImageSplatRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/checkout'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/info'
    | '/landing-editor'
    | '/new-password'
    | '/overlay-creator'
    | '/plans'
    | '/recharge'
    | '/referrals'
    | '/editor/$projectId'
    | '/api/public/landing-image/$'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/checkout'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/info'
    | '/landing-editor'
    | '/new-password'
    | '/overlay-creator'
    | '/plans'
    | '/recharge'
    | '/referrals'
    | '/editor/$projectId'
    | '/api/public/landing-image/$'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/app'
    | '/auth'
    | '/checkout'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/info'
    | '/_authenticated/landing-editor'
    | '/_authenticated/new-password'
    | '/_authenticated/overlay-creator'
    | '/_authenticated/plans'
    | '/_authenticated/recharge'
    | '/_authenticated/referrals'
    | '/_authenticated/editor/$projectId'
    | '/api/public/landing-image/$'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  ApiPublicLandingImageSplatRoute: typeof ApiPublicLandingImageSplatRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/info': {
      id: '/_authenticated/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof AuthenticatedInfoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/landing-editor': {
      id: '/_authenticated/landing-editor'
      path: '/landing-editor'
      fullPath: '/landing-editor'
      preLoaderRoute: typeof AuthenticatedLandingEditorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-password': {
      id: '/_authenticated/new-password'
      path: '/new-password'
      fullPath: '/new-password'
      preLoaderRoute: typeof AuthenticatedNewPasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overlay-creator': {
      id: '/_authenticated/overlay-creator'
      path: '/overlay-creator'
      fullPath: '/overlay-creator'
      preLoaderRoute: typeof AuthenticatedOverlayCreatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans': {
      id: '/_authenticated/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthenticatedPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recharge': {
      id: '/_authenticated/recharge'
      path: '/recharge'
      fullPath: '/recharge'
      preLoaderRoute: typeof AuthenticatedRechargeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/editor/$projectId': {
      id: '/_authenticated/editor/$projectId'
      path: '/editor/$projectId'
      fullPath: '/editor/$projectId'
      preLoaderRoute: typeof AuthenticatedEditorProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/landing-image/$': {
      id: '/api/public/landing-image/$'
      path: '/api/public/landing-image/$'
      fullPath: '/api/public/landing-image/$'
      preLoaderRoute: typeof ApiPublicLandingImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInfoRoute: typeof AuthenticatedInfoRoute
  AuthenticatedLandingEditorRoute: typeof AuthenticatedLandingEditorRoute
  AuthenticatedNewPasswordRoute: typeof AuthenticatedNewPasswordRoute
  AuthenticatedOverlayCreatorRoute: typeof AuthenticatedOverlayCreatorRoute
  AuthenticatedPlansRoute: typeof AuthenticatedPlansRoute
  AuthenticatedRechargeRoute: typeof AuthenticatedRechargeRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
  AuthenticatedEditorProjectIdRoute: typeof AuthenticatedEditorProjectIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInfoRoute: AuthenticatedInfoRoute,
  AuthenticatedLandingEditorRoute: AuthenticatedLandingEditorRoute,
  AuthenticatedNewPasswordRoute: AuthenticatedNewPasswordRoute,
  AuthenticatedOverlayCreatorRoute: AuthenticatedOverlayCreatorRoute,
  AuthenticatedPlansRoute: AuthenticatedPlansRoute,
  AuthenticatedRechargeRoute: AuthenticatedRechargeRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
  AuthenticatedEditorProjectIdRoute: AuthenticatedEditorProjectIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  ApiPublicLandingImageSplatRoute: ApiPublicLandingImageSplatRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
