/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCriadorDeOverlayRouteImport } from './routes/_authenticated/criador-de-overlay'
import { Route as AuthenticatedEditorProjectIdRouteImport } from './routes/_authenticated/editor.$projectId'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCriadorDeOverlayRoute =
  AuthenticatedCriadorDeOverlayRouteImport.update({
    id: '/_authenticated/criador-de-overlay',
    path: '/criador-de-overlay',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedEditorProjectIdRoute =
  AuthenticatedEditorProjectIdRouteImport.update({
    id: '/_authenticated/editor/$projectId',
    path: '/editor/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRoute
  '/criador-de-overlay': typeof AuthenticatedCriadorDeOverlayRoute
  '/': typeof AuthenticatedIndexRoute
  '/editor/$projectId': typeof AuthenticatedEditorProjectIdRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppRoute
  '/criador-de-overlay': typeof AuthenticatedCriadorDeOverlayRoute
  '/': typeof AuthenticatedIndexRoute
  '/editor/$projectId': typeof AuthenticatedEditorProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRoute
  '/_authenticated/criador-de-overlay': typeof AuthenticatedCriadorDeOverlayRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/editor/$projectId': typeof AuthenticatedEditorProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/app' | '/criador-de-overlay' | '/' | '/editor/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to: '/app' | '/criador-de-overlay' | '/' | '/editor/$projectId'
  id:
    | '__root__'
    | '/app'
    | '/_authenticated/criador-de-overlay'
    | '/_authenticated/'
    | '/_authenticated/editor/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRoute
  AuthenticatedCriadorDeOverlayRoute: typeof AuthenticatedCriadorDeOverlayRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedEditorProjectIdRoute: typeof AuthenticatedEditorProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/criador-de-overlay': {
      id: '/_authenticated/criador-de-overlay'
      path: '/criador-de-overlay'
      fullPath: '/criador-de-overlay'
      preLoaderRoute: typeof AuthenticatedCriadorDeOverlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/editor/$projectId': {
      id: '/_authenticated/editor/$projectId'
      path: '/editor/$projectId'
      fullPath: '/editor/$projectId'
      preLoaderRoute: typeof AuthenticatedEditorProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRoute,
  AuthenticatedCriadorDeOverlayRoute: AuthenticatedCriadorDeOverlayRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedEditorProjectIdRoute: AuthenticatedEditorProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
